### ISSUE TITLE
Error in fn_showWeaponInfo

### ISSUE THREAD

**Issue by McDiod** [DerZade/grad_minui#4]
```
20:25:54 Error in expression <mode"): { 
private _currentWeaponMode = tolower currentWeaponMode player;
privat>
20:25:54   Error position: <tolower currentWeaponMode player;
privat>
20:25:54   Error tolower: Type Number, expected String
20:25:54 File \grad_minui_weaponInfo\functions\fn_showWeaponInfo.sqf [grad_minui_fnc_showWeaponInfo], line 32
```

Happened on end of mission.

See:
https://community.bistudio.com/wiki/currentWeaponMode
> (currentWeaponMode) will return 0 Number if given object is a vehicle instead of a person.

**Comment by DerZade** [comment]
Acknowledged. 
This seems to occure with no vehicle as a factor. 

Best solution would be to just exit the function if `currentWeaponMode` returns a number. 
https://github.com/DerZade/grad_minui/blob/master/addons/grad_minui_weaponinfo/functions/fn_showWeaponInfo.sqf#L32
